run:
	dotnet run

run-watch:
	dotnet watch run

db-remove:
	dotnet ef database update 0

db-migration:
	dotnet ef migrations add Inital
	dotnet ef database update

db-update:
	dotnet ef database update